# Generated by Django 2.2 on 2019-04-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_unit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='last_name',
        ),
    ]
