# Generated by Django 2.2 on 2019-04-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190403_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='first_name',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='unit',
            name='last_name',
            field=models.CharField(default='Asd', max_length=30),
            preserve_default=False,
        ),
    ]
