# Generated by Django 2.2 on 2019-04-03 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190403_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='Image',
        ),
    ]
