# Generated by Django 2.2 on 2019-04-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20190403_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='first_name',
            new_name='gif_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='last_name',
        ),
    ]
