# Generated by Django 2.2 on 2019-04-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_auto_20190404_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='uri_path',
            field=models.TextField(default='', null=True),
        ),
    ]
